/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xiat_client;

import javax.swing.JOptionPane;

/**
 *
 * @author Joan Galiana Magán
 */
public class Login extends javax.swing.JFrame {

    String server;
    String nick;
    boolean datos = false;
    Xiat_Client cliente;
    int puerto;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     *
     * @param cliente
     */
    public Login(Xiat_Client cliente) {
        initComponents();
        this.cliente = cliente;
    }

    /**
     *
     * @return
     */
    public String getIP() {
        return server;
    }

    /**
     *
     * @return
     */
    public String getNick() {
        return nick;
    }

    /**
     *
     * @return
     */
    public int getPuerto() {
        return puerto;
    }

    private void lee() {
        server = entradaIP.getText();
        nick = entradaNombre.getText();
        if (server.isEmpty() || nick.isEmpty()) {//falta comprobacion de puerto vacio
            error("Completa los dos campooos!!", "Letrasao!");
        } else {
            if (!validaPuerto()) {
                error("El puerto no es validoo!", "Puerto mal");
            } else {
                if (!compruebaIP(server)) {
                    error("La ip no es valida!!!!", "IP mal");
                } else {
                    this.setVisible(false);
                    datos = true;
                    cliente.getLogin();
                }
            }
        }
    }

    private void error(String error, String titulo) {
        JOptionPane.showMessageDialog(this,
                error,
                titulo,
                JOptionPane.ERROR_MESSAGE);
    }

    private boolean compruebaIP(String ip) {
        String arr[];
        arr = ip.split("\\.");
        if (arr.length != 4) {
            return false;
        }
        for (String x : arr) {
            try {
                int numero = Integer.parseInt(x);
                if (numero > 254 || numero < 0) {
                    return false;
                }
            } catch (Exception e) {
                return false;
            }

        }
        return true;
    }

    private boolean validaPuerto() {
        try {
            puerto = Integer.parseInt(entradaPuerto.getText());
        } catch (Exception e) {
            return false;
        }
        if (puerto <= 0) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entradaIP = new javax.swing.JTextField();
        entradaNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonEnviar = new javax.swing.JButton();
        entradaPuerto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 160));
        setResizable(false);

        entradaIP.setText("192.168.3.206");
        entradaIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaIPActionPerformed(evt);
            }
        });

        entradaNombre.setText("Estanteria");
        entradaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nick");

        jLabel2.setText("IP  Puerto");

        botonEnviar.setText("Enviar");
        botonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonEnviarMouseReleased(evt);
            }
        });

        entradaPuerto.setText("5050");
        entradaPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaPuertoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entradaIP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(entradaPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entradaIP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entradaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNombreActionPerformed

    private void botonEnviarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEnviarMouseReleased
        lee();
    }//GEN-LAST:event_botonEnviarMouseReleased

    private void entradaPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaPuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaPuertoActionPerformed

    private void entradaIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JTextField entradaIP;
    private javax.swing.JTextField entradaNombre;
    private javax.swing.JTextField entradaPuerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
